### PR TITLE
Update to 1.11.5

### PR DESCRIPTION
**Pull request by Beryesa**
Includes commits from #8 
Minor update for bot checks
External-data-checker should handle it when merged.

### CODE REVIEW

**Comment by Beryesa** [comment]
Ping @hfiguiere @olea =)

**Comment by olea** [comment]
> Ping @hfiguiere @olea =)

Probable @hfiguiere should approve the patch better than me. I have neglected the project for too long :-/

**Comment by hfiguiere** [comment]
I know nothing about that app.

I can merge, but that's it.

**Comment by Beryesa** [comment]
What should I do?

**Comment by hfiguiere** [comment]
I guess the maintainer is not interested.

bot, build

**Comment by Beryesa** [comment]
From now on, flathub's external data checker should automate it, but I don't know if it's merged automatically or if it just makes a pull request.
I use this app regularly, how can I request maintainership, (unless the upstream themselves get interested) to keep this up to date?

**Pull request merged**
